// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// IMPORTANT: Run `flutterfire configure` to generate your own Firebase options.
/// These are placeholder values that need to be replaced with your actual
/// Firebase project configuration.
///
/// Example:
/// ```sh
/// # Install FlutterFire CLI
/// dart pub global activate flutterfire_cli
///
/// # Generate firebase_options.dart
/// flutterfire configure
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Replace these placeholder values with your actual Firebase project configuration
  // Run `flutterfire configure` to generate real values

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO7qRXkc-jC-f-pz0YMCsdBshSqeqSS8M',
    appId: '1:204775861740:android:b9393433bf150a0967a4c9',
    messagingSenderId: '204775861740',
    projectId: 'receiptvault-app',
    storageBucket: 'receiptvault-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEqILupp_8w4CncxCIP7lAlyh2jMqXxGY',
    appId: '1:204775861740:ios:87572b92408f8c0267a4c9',
    messagingSenderId: '204775861740',
    projectId: 'receiptvault-app',
    storageBucket: 'receiptvault-app.firebasestorage.app',
    iosClientId: '204775861740-jt19iqv3q684rut1i0t3hva42ce9adh1.apps.googleusercontent.com',
    iosBundleId: 'com.receiptvault.receiptVault',
  );

}